export interface Country {
  id: string;
  name: string;
  region: 'Northern' | 'Western' | 'Eastern' | 'Central' | 'Southern';
  gdp: number; // in billions USD
  population: number; // in millions
  unemployment: number; // percentage
  debtToGdp: number; // percentage
  budget: number; // in billions USD
  highlight: string;
  growthRate: number; // percentage
  year?: number;
}

export const COUNTRIES: Country[] = [
  // Northern Africa (7 countries, total GDP $623.8B, avg unemployment ~12.1%)
  {
    id: 'egypt',
    name: 'Egypt',
    region: 'Northern',
    gdp: 469.4,
    population: 109.3,
    unemployment: 7.4,
    debtToGdp: 88.5,
    budget: 22.1,
    highlight: 'Growing tech sector and service economy',
    growthRate: 4.2,
    year: 2026,
  },
  {
    id: 'algeria',
    name: 'Algeria',
    region: 'Northern',
    gdp: 87.2,
    population: 44.9,
    unemployment: 11.5,
    debtToGdp: 52.4,
    budget: 6.8,
    highlight: 'Hydrocarbon dominated export leader',
    growthRate: 2.8,
    year: 2026,
  },
  {
    id: 'morocco',
    name: 'Morocco',
    region: 'Northern',
    gdp: 52.5,
    population: 37.4,
    unemployment: 12.9,
    debtToGdp: 69.1,
    budget: 3.9,
    highlight: 'Manufacturing and tourism hub',
    growthRate: 3.1,
    year: 2026,
  },
  {
    id: 'tunisia',
    name: 'Tunisia',
    region: 'Northern',
    gdp: 8.9,
    population: 12.3,
    unemployment: 15.2,
    debtToGdp: 79.8,
    budget: 0.9,
    highlight: 'Diverse industrial exports and tourism',
    growthRate: 1.2,
    year: 2026,
  },
  {
    id: 'libya',
    name: 'Libya',
    region: 'Northern',
    gdp: 4.1,
    population: 6.8,
    unemployment: 19.3,
    debtToGdp: 12.0,
    budget: 0.5,
    highlight: 'Rebuilding oil production capacity',
    growthRate: 5.6,
    year: 2026,
  },
  {
    id: 'sudan',
    name: 'Sudan',
    region: 'Northern',
    gdp: 1.2,
    population: 46.8,
    unemployment: 17.1,
    debtToGdp: 124.0,
    budget: 0.2,
    highlight: 'Agricultural potential seeking stabilization',
    growthRate: -2.5,
    year: 2026,
  },
  {
    id: 'mauritania',
    name: 'Mauritania',
    region: 'Northern',
    gdp: 0.5,
    population: 4.7,
    unemployment: 11.3,
    debtToGdp: 48.5,
    budget: 0.1,
    highlight: 'Expanding mining and gas sectors',
    growthRate: 4.0,
    year: 2026,
  },

  // Western Africa (16 countries, total GDP $789.2B, avg unemployment ~8.4%)
  {
    id: 'nigeria',
    name: 'Nigeria',
    region: 'Western',
    gdp: 440.8,
    population: 218.5,
    unemployment: 8.1,
    debtToGdp: 38.0,
    budget: 25.4,
    highlight: 'Largest economy and population in Africa',
    growthRate: 3.1,
    year: 2026,
  },
  {
    id: 'ghana',
    name: 'Ghana',
    region: 'Western',
    gdp: 145.2,
    population: 33.4,
    unemployment: 4.5,
    debtToGdp: 82.0,
    budget: 8.5,
    highlight: 'Gold and cocoa exporter with active tech hub',
    growthRate: 3.8,
    year: 2026,
  },
  {
    id: 'ivory-coast',
    name: 'Ivory Coast',
    region: 'Western',
    gdp: 90.5,
    population: 28.1,
    unemployment: 3.2,
    debtToGdp: 56.1,
    budget: 5.1,
    highlight: 'Leading global cocoa producer, high growth',
    growthRate: 6.5,
    year: 2026,
  },
  {
    id: 'senegal',
    name: 'Senegal',
    region: 'Western',
    gdp: 40.2,
    population: 17.3,
    unemployment: 6.8,
    debtToGdp: 72.4,
    budget: 2.1,
    highlight: 'Striving regional financial and political hub',
    growthRate: 5.3,
    year: 2026,
  },
  {
    id: 'mali',
    name: 'Mali',
    region: 'Western',
    gdp: 20.1,
    population: 22.5,
    unemployment: 7.9,
    debtToGdp: 53.2,
    budget: 1.1,
    highlight: 'Gold mining and agricultural economy',
    growthRate: 3.5,
    year: 2026,
  },
  {
    id: 'burkina-faso',
    name: 'Burkina Faso',
    region: 'Western',
    gdp: 18.3,
    population: 22.6,
    unemployment: 6.4,
    debtToGdp: 55.0,
    budget: 0.9,
    highlight: 'Gold exporter seeking supply chain safety',
    growthRate: 3.2,
    year: 2026,
  },
  {
    id: 'niger',
    name: 'Niger',
    region: 'Western',
    gdp: 12.4,
    population: 26.2,
    unemployment: 14.8,
    debtToGdp: 51.2,
    budget: 0.6,
    highlight: 'Uranium reserves and agriculture focus',
    growthRate: 4.1,
    year: 2026,
  },
  {
    id: 'guinea',
    name: 'Guinea',
    region: 'Western',
    gdp: 8.5,
    population: 13.8,
    unemployment: 5.3,
    debtToGdp: 42.1,
    budget: 0.4,
    highlight: 'World-class bauxite reserves development',
    growthRate: 5.0,
    year: 2026,
  },
  {
    id: 'benin',
    name: 'Benin',
    region: 'Western',
    gdp: 4.8,
    population: 13.3,
    unemployment: 2.1,
    debtToGdp: 54.0,
    budget: 0.25,
    highlight: 'Cotonou port trade and cotton expansion',
    growthRate: 5.8,
    year: 2026,
  },
  {
    id: 'togo',
    name: 'Togo',
    region: 'Western',
    gdp: 3.1,
    population: 8.8,
    unemployment: 4.1,
    debtToGdp: 70.3,
    budget: 0.15,
    highlight: 'Phosphate mining and deepwater transit port',
    growthRate: 5.2,
    year: 2026,
  },
  {
    id: 'sierra-leone',
    name: 'Sierra Leone',
    region: 'Western',
    gdp: 2.5,
    population: 8.6,
    unemployment: 5.1,
    debtToGdp: 76.5,
    budget: 0.12,
    highlight: 'Diamond reserves and mineral development',
    growthRate: 2.9,
    year: 2026,
  },
  {
    id: 'liberia',
    name: 'Liberia',
    region: 'Western',
    gdp: 1.8,
    population: 5.3,
    unemployment: 4.0,
    debtToGdp: 53.8,
    budget: 0.1,
    highlight: 'Iron ore and maritime registry revenue',
    growthRate: 3.4,
    year: 2026,
  },
  {
    id: 'gambia',
    name: 'Gambia',
    region: 'Western',
    gdp: 0.6,
    population: 2.7,
    unemployment: 9.5,
    debtToGdp: 81.2,
    budget: 0.05,
    highlight: 'Tourism and peanut production focus',
    growthRate: 4.5,
    year: 2026,
  },
  {
    id: 'guinea-bissau',
    name: 'Guinea-Bissau',
    region: 'Western',
    gdp: 0.3,
    population: 2.1,
    unemployment: 6.2,
    debtToGdp: 78.4,
    budget: 0.02,
    highlight: 'Cashew nut exporter with coastal resources',
    growthRate: 3.0,
    year: 2026,
  },
  {
    id: 'cabo-verde',
    name: 'Cabo Verde',
    region: 'Western',
    gdp: 0.15,
    population: 0.59,
    unemployment: 12.2,
    debtToGdp: 115.0,
    budget: 0.01,
    highlight: 'Service-oriented island economy',
    growthRate: 4.8,
    year: 2026,
  },
  {
    id: 'saint-helena',
    name: 'Saint Helena Area',
    region: 'Western',
    gdp: 0.05,
    population: 0.01,
    unemployment: 1.5,
    debtToGdp: 5.0,
    budget: 0.005,
    highlight: 'Remote island economy with fishing',
    growthRate: 1.0,
    year: 2026,
  },

  // Eastern Africa (14 countries, total GDP $445.6B, avg unemployment ~6.8%)
  {
    id: 'ethiopia',
    name: 'Ethiopia',
    region: 'Eastern',
    gdp: 205.4,
    population: 123.4,
    unemployment: 8.0,
    debtToGdp: 46.4,
    budget: 10.2,
    highlight: 'Rapid industrial park expansion, airline hub',
    growthRate: 6.1,
    year: 2026,
  },
  {
    id: 'kenya',
    name: 'Kenya',
    region: 'Eastern',
    gdp: 110.3,
    population: 54.0,
    unemployment: 5.6,
    debtToGdp: 68.2,
    budget: 7.1,
    highlight: 'Silicon Savannah tech hub, tea and services',
    growthRate: 5.0,
    year: 2026,
  },
  {
    id: 'tanzania',
    name: 'Tanzania',
    region: 'Eastern',
    gdp: 75.8,
    population: 65.5,
    unemployment: 2.7,
    debtToGdp: 41.5,
    budget: 4.5,
    highlight: 'Gold, natural gas, and wildlife tourism leader',
    growthRate: 5.4,
    year: 2026,
  },
  {
    id: 'uganda',
    name: 'Uganda',
    region: 'Eastern',
    gdp: 40.5,
    population: 47.2,
    unemployment: 2.9,
    debtToGdp: 50.8,
    budget: 2.3,
    highlight: 'Agricultural heartland preparing for oil extraction',
    growthRate: 5.5,
    year: 2026,
  },
  {
    id: 'rwanda',
    name: 'Rwanda',
    region: 'Eastern',
    gdp: 11.2,
    population: 13.8,
    unemployment: 15.1,
    debtToGdp: 61.3,
    budget: 1.1,
    highlight: 'High-performing ease of doing business leader',
    growthRate: 7.2,
    year: 2026,
  },
  {
    id: 'burundi',
    name: 'Burundi',
    region: 'Eastern',
    gdp: 0.8,
    population: 12.9,
    unemployment: 1.8,
    debtToGdp: 66.4,
    budget: 0.08,
    highlight: 'Coffee exporter striving for growth booster',
    growthRate: 3.3,
    year: 2026,
  },
  {
    id: 'somalia',
    name: 'Somalia',
    region: 'Eastern',
    gdp: 0.6,
    population: 17.6,
    unemployment: 13.1,
    debtToGdp: 9.0,
    budget: 0.06,
    highlight: 'Livestock exports and expanding digital sector',
    growthRate: 2.7,
    year: 2026,
  },
  {
    id: 'south-sudan',
    name: 'South Sudan',
    region: 'Eastern',
    gdp: 0.4,
    population: 10.9,
    unemployment: 12.0,
    debtToGdp: 62.0,
    budget: 0.04,
    highlight: 'Oil reserves seeking transport diversification',
    growthRate: 1.1,
    year: 2026,
  },
  {
    id: 'djibouti',
    name: 'Djibouti',
    region: 'Eastern',
    gdp: 0.3,
    population: 1.1,
    unemployment: 26.1,
    debtToGdp: 72.0,
    budget: 0.03,
    highlight: 'Strategic maritime logistics and port focus',
    growthRate: 4.5,
    year: 2026,
  },
  {
    id: 'eritrea',
    name: 'Eritrea',
    region: 'Eastern',
    gdp: 0.2,
    population: 3.6,
    unemployment: 6.4,
    debtToGdp: 121.0,
    budget: 0.02,
    highlight: 'Mining and agricultural developments',
    growthRate: 2.1,
    year: 2026,
  },
  {
    id: 'madagascar',
    name: 'Madagascar',
    region: 'Eastern',
    gdp: 0.05,
    population: 29.6,
    unemployment: 1.9,
    debtToGdp: 52.4,
    budget: 0.01,
    highlight: 'Vanilla production leader, biodiversity tourism',
    growthRate: 4.2,
    year: 2026,
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    region: 'Eastern',
    gdp: 0.03,
    population: 1.3,
    unemployment: 6.8,
    debtToGdp: 80.1,
    budget: 0.008,
    highlight: 'Financial services, high income tourist hub',
    growthRate: 5.1,
    year: 2026,
  },
  {
    id: 'seychelles',
    name: 'Seychelles',
    region: 'Eastern',
    gdp: 0.01,
    population: 0.1,
    unemployment: 3.5,
    debtToGdp: 68.4,
    budget: 0.005,
    highlight: 'Blue economy pioneer, luxury tourism hub',
    growthRate: 3.9,
    year: 2026,
  },
  {
    id: 'comoros',
    name: 'Comoros',
    region: 'Eastern',
    gdp: 0.01,
    population: 0.84,
    unemployment: 6.1,
    debtToGdp: 35.0,
    budget: 0.002,
    highlight: 'Ylang-ylang oil, vanilla, and clove producer',
    growthRate: 2.5,
    year: 2026,
  },

  // Southern Africa (9 countries)
  {
    id: 'south-africa',
    name: 'South Africa',
    region: 'Southern',
    gdp: 419.0,
    population: 60.4,
    unemployment: 29.8,
    debtToGdp: 71.0,
    budget: 45.1,
    highlight: 'Most industrialized, advanced financial system',
    growthRate: 1.5,
    year: 2026,
  },
  {
    id: 'zimbabwe',
    name: 'Zimbabwe',
    region: 'Southern',
    gdp: 28.3,
    population: 16.3,
    unemployment: 16.4,
    debtToGdp: 95.0,
    budget: 2.2,
    highlight: 'Rich mineral resources seeking monetary reform',
    growthRate: 2.0,
    year: 2026,
  },
  {
    id: 'zambia',
    name: 'Zambia',
    region: 'Southern',
    gdp: 29.1,
    population: 20.0,
    unemployment: 12.5,
    debtToGdp: 110.0,
    budget: 1.9,
    highlight: 'Major copper producer undergoing debt restructuring',
    growthRate: 4.1,
    year: 2026,
  },
  {
    id: 'mozambique',
    name: 'Mozambique',
    region: 'Southern',
    gdp: 18.4,
    population: 33.0,
    unemployment: 15.0,
    debtToGdp: 102.0,
    budget: 1.1,
    highlight: 'Enormous offshore liquefied natural gas reserves',
    growthRate: 5.5,
    year: 2026,
  },
  {
    id: 'namibia',
    name: 'Namibia',
    region: 'Southern',
    gdp: 12.6,
    population: 2.6,
    unemployment: 20.5,
    debtToGdp: 68.0,
    budget: 1.2,
    highlight: 'Uranium, diamond exporter, green hydrogen plans',
    growthRate: 3.5,
    year: 2026,
  },
  {
    id: 'botswana',
    name: 'Botswana',
    region: 'Southern',
    gdp: 1.5,
    population: 2.6,
    unemployment: 23.1,
    debtToGdp: 20.4,
    budget: 1.8,
    highlight: 'Highly stable diamond exporter, nature tourism',
    growthRate: 3.2,
    year: 2026,
  },
  {
    id: 'lesotho',
    name: 'Lesotho',
    region: 'Southern',
    gdp: 0.5,
    population: 2.3,
    unemployment: 22.4,
    debtToGdp: 53.0,
    budget: 0.2,
    highlight: 'Water exports and textile manufacturing hub',
    growthRate: 1.8,
    year: 2026,
  },
  {
    id: 'eswatini',
    name: 'Eswatini',
    region: 'Southern',
    gdp: 0.3,
    population: 1.2,
    unemployment: 21.8,
    debtToGdp: 43.1,
    budget: 0.15,
    highlight: 'Agro-processing and textile exports leader',
    growthRate: 2.1,
    year: 2026,
  },
  {
    id: 'malawi',
    name: 'Malawi',
    region: 'Southern',
    gdp: 0.1,
    population: 20.4,
    unemployment: 6.3,
    debtToGdp: 75.0,
    budget: 0.3,
    highlight: 'Agriculture dependent seeking industrial diversification',
    growthRate: 2.8,
    year: 2026,
  },

  // Central Africa (9 countries, total GDP $187.3B, avg unemployment ~9.7%)
  {
    id: 'dr-congo',
    name: 'DR Congo',
    region: 'Central',
    gdp: 135.2,
    population: 99.0,
    unemployment: 18.0,
    debtToGdp: 15.4,
    budget: 5.4,
    highlight: 'Unrivaled cobalt and copper mineral reserves',
    growthRate: 6.2,
    year: 2026,
  },
  {
    id: 'cameroon',
    name: 'Cameroon',
    region: 'Central',
    gdp: 35.4,
    population: 27.9,
    unemployment: 3.8,
    debtToGdp: 45.1,
    budget: 2.1,
    highlight: 'Diversified agricultural and industrial economy',
    growthRate: 4.0,
    year: 2026,
  },
  {
    id: 'angola',
    name: 'Angola',
    region: 'Central',
    gdp: 12.5,
    population: 35.6,
    unemployment: 14.5,
    debtToGdp: 63.3,
    budget: 4.8,
    highlight: 'Major oil producer pursuing sector diversifications',
    growthRate: 3.0,
    year: 2026,
  },
  {
    id: 'congo-rep',
    name: 'Republic of the Congo',
    region: 'Central',
    gdp: 2.5,
    population: 6.0,
    unemployment: 21.0,
    debtToGdp: 90.0,
    budget: 0.35,
    highlight: 'Oil exporter with massive peatland sinks',
    growthRate: 2.5,
    year: 2026,
  },
  {
    id: 'gabon',
    name: 'Gabon',
    region: 'Central',
    gdp: 1.1,
    population: 2.4,
    unemployment: 20.1,
    debtToGdp: 61.2,
    budget: 0.45,
    highlight: 'High forest cover, manganese and oil exports',
    growthRate: 2.7,
    year: 2026,
  },
  {
    id: 'equatorial-guinea',
    name: 'Equatorial Guinea',
    region: 'Central',
    gdp: 0.4,
    population: 1.7,
    unemployment: 9.1,
    debtToGdp: 41.5,
    budget: 0.3,
    highlight: 'Hydrocarbon producer seeking service pivot',
    growthRate: -1.5,
    year: 2026,
  },
  {
    id: 'chad',
    name: 'Chad',
    region: 'Central',
    gdp: 0.15,
    population: 17.7,
    unemployment: 1.4,
    debtToGdp: 48.0,
    budget: 0.1,
    highlight: 'Oil producer seeking transit infrastructure',
    growthRate: 3.1,
    year: 2026,
  },
  {
    id: 'central-african-republic',
    name: 'Central African Republic',
    region: 'Central',
    gdp: 0.04,
    population: 5.6,
    unemployment: 6.4,
    debtToGdp: 55.2,
    budget: 0.05,
    highlight: 'Rich timber and diamond reserves potential',
    growthRate: 1.5,
    year: 2026,
  },
  {
    id: 'sao-tome',
    name: 'Sao Tome & Principe',
    region: 'Central',
    gdp: 0.01,
    population: 0.23,
    unemployment: 13.5,
    debtToGdp: 85.0,
    budget: 0.01,
    highlight: 'Small island agriculture and tourism',
    growthRate: 2.0,
    year: 2026,
  },
];
